#!/usr/bin/env bash
#
# One-time setup for DagrofaShield git-push-to-deploy, run ON THE BOX
# (192.168.86.163) as the `home` user - not from your local machine.
#
# Everything lives under /opt/dagrofashield/ - `home` already owns /opt
# itself (home:root, mode 755) on this box, so creating a subdirectory
# there needs no sudo. This script never calls sudo, for anything: if
# /opt turns out not to be writable by `home` after all, it stops and
# reports that rather than guessing at how to get access.
#
# This box also runs several unrelated personal services (Home Assistant,
# Node-RED, Zigbee2MQTT, Mosquitto, MariaDB, InfluxDB, code-server,
# Duplicati, Portainer, ...) under their own /opt/<service>/ directories,
# tied together by a separate /opt/docker-compose.yaml and /opt/.env.
# This script never touches those, and never runs anything from /opt
# itself - only from /opt/dagrofashield/deploy.
#
# Usage:
#   scp -r deploy home@192.168.86.163:~/dagrofashield-setup
#   ssh home@192.168.86.163
#   cd ~/dagrofashield-setup && ./setup-box.sh
#
# Idempotent: safe to re-run. It will NOT overwrite an existing secrets
# .env (so re-running never rotates your Postgres password out from under
# a running database), and it will NOT touch any docker volume.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOX_ROOT="/opt/dagrofashield"
GIT_DIR="$BOX_ROOT/dagrofashield.git"
WORK_TREE="$BOX_ROOT/deploy"
ENV_FILE="$BOX_ROOT/.env"

echo "== Creating $BOX_ROOT =="
if ! mkdir -p "$BOX_ROOT" 2>/dev/null; then
    echo "ERROR: cannot create $BOX_ROOT - '$(whoami)' does not have write access to /opt." >&2
    echo "This script never calls sudo itself. This box is expected to have /opt" >&2
    echo "owned by home:root, mode 755 - if that's not the case, fix ownership" >&2
    echo "(as whoever has the access to do so) before re-running this script." >&2
    exit 1
fi
if [ ! -w "$BOX_ROOT" ]; then
    echo "ERROR: $BOX_ROOT exists but is not writable by '$(whoami)'." >&2
    exit 1
fi
echo "OK: $BOX_ROOT exists and is writable by $(whoami)."

echo "== Checking Docker access (no sudo) =="
if ! docker ps >/dev/null 2>&1; then
    echo "ERROR: 'docker ps' failed for user '$(whoami)' without sudo." >&2
    echo "This setup refuses to silently prefix every docker command with sudo." >&2
    echo "'$(whoami)' is expected to already be in the docker group on this box -" >&2
    echo "if not, that needs fixing (by someone with the access to do so) first." >&2
    exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
    echo "ERROR: 'docker compose version' failed. Is the Compose plugin installed?" >&2
    exit 1
fi
echo "OK: docker + docker compose usable without sudo."

echo "== Bare repo: $GIT_DIR =="
if [ -f "$GIT_DIR/HEAD" ]; then
    echo "Already initialized, leaving as-is."
else
    git init --bare "$GIT_DIR"
fi

echo "== Deploy worktree: $WORK_TREE =="
mkdir -p "$WORK_TREE"

echo "== Secrets: $ENV_FILE =="
if [ -f "$ENV_FILE" ]; then
    echo "Already exists - leaving untouched (not rotating an existing DB password)."
else
    umask 077
    {
        echo "# Generated by setup-box.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        echo "# LAN-only test deploy - never commit this file, never echo it to a shared terminal."
        echo
        echo "POSTGRES_USER=dagrofashield"
        # hex, not base64: base64 output can contain '/' or '+', which
        # corrupts the postgresql://user:PASSWORD@host:port/db connection
        # string it gets embedded into unescaped (docker-compose.yml's
        # DATABASE_URL) - Prisma fails with "invalid port number in
        # database URL" the moment the password happens to contain a '/'.
        # Hex is always URL-safe.
        echo "POSTGRES_PASSWORD=$(openssl rand -hex 32)"
        echo "POSTGRES_DB=dagrofashield"
        echo
        echo "JWT_ACCESS_SECRET=$(openssl rand -base64 48)"
        echo "JWT_ACCESS_EXPIRES_IN=15m"
        echo "JWT_REFRESH_EXPIRES_IN=7d"
        echo
        echo "# Public LAN URL of the frontend - used for CORS."
        echo "FRONTEND_ORIGIN=http://192.168.86.163:3000"
        echo
        echo "# Entra ID / OIDC left blank on purpose: the app boots with Entra"
        echo "# disabled and falls back to the local seeded admin account only."
        echo "# See backend/src/common/config/env.validation.ts - Entra vars are"
        echo "# intentionally not required."
        echo "ENTRA_TENANT_ID="
        echo "ENTRA_CLIENT_ID="
        echo "ENTRA_CLIENT_SECRET="
        echo "ENTRA_REDIRECT_URI="
    } >"$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "Generated $ENV_FILE (mode 600). Contents not printed - see the file"
    echo "directly on the box if you need to inspect it."
fi

echo "== Installing post-receive hook =="
install -m 0755 "$HERE/post-receive" "$GIT_DIR/hooks/post-receive"
echo "Installed $GIT_DIR/hooks/post-receive"

cat <<EOF

Setup complete.

Next, from your LOCAL machine:
  git remote add box ssh://home@192.168.86.163/opt/dagrofashield/dagrofashield.git
  git push box main

Then tail the deploy log on the box:
  tail -f $BOX_ROOT/deploy.log
EOF
