#!/usr/bin/env bash
#
# One-time setup for DagrofaShield git-push-to-deploy, run ON THE BOX
# (192.168.86.163) as the `home` user - not from your local machine.
#
# Deploys under /opt, which `home` does not own by default. This script
# NEVER calls sudo itself - it expects the three directories below to
# already exist and be owned by `home` before you run it:
#
#   sudo mkdir -p /opt/dagrofashield.git /opt/dagrofashield-deploy /opt/dagrofashield-secrets
#   sudo chown -R home:home /opt/dagrofashield.git /opt/dagrofashield-deploy /opt/dagrofashield-secrets
#
# Usage (after the above):
#   scp -r deploy home@192.168.86.163:~/dagrofashield-setup
#   ssh home@192.168.86.163
#   cd ~/dagrofashield-setup && ./setup-box.sh
#
# Idempotent: safe to re-run. It will NOT overwrite an existing secrets
# .env (so re-running never rotates your Postgres password out from under
# a running database), and it will NOT touch any docker volume.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GIT_DIR="/opt/dagrofashield.git"
WORK_TREE="/opt/dagrofashield-deploy"
SECRETS_DIR="/opt/dagrofashield-secrets"
ENV_FILE="$SECRETS_DIR/.env"

echo "== Checking /opt directories are pre-created and owned by $(whoami) =="
for dir in "$GIT_DIR" "$WORK_TREE" "$SECRETS_DIR"; do
    if [ ! -d "$dir" ] || [ ! -w "$dir" ]; then
        echo "ERROR: $dir does not exist or is not writable by '$(whoami)'." >&2
        echo "This script never calls sudo itself. Run this once first, then re-run:" >&2
        echo "  sudo mkdir -p $GIT_DIR $WORK_TREE $SECRETS_DIR" >&2
        echo "  sudo chown -R $(whoami):$(whoami) $GIT_DIR $WORK_TREE $SECRETS_DIR" >&2
        exit 1
    fi
done
echo "OK: all three /opt paths exist and are writable by $(whoami)."

echo "== Checking Docker access (no sudo) =="
if ! docker ps >/dev/null 2>&1; then
    echo "ERROR: 'docker ps' failed for user '$(whoami)' without sudo." >&2
    echo "This setup refuses to silently prefix every docker command with sudo." >&2
    echo "Add '$(whoami)' to the docker group (sudo usermod -aG docker $(whoami)," >&2
    echo "then log out/in) and re-run this script." >&2
    exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
    echo "ERROR: 'docker compose version' failed. Is the Compose plugin installed?" >&2
    exit 1
fi
echo "OK: docker + docker compose usable without sudo."

echo "== Bare repo: $GIT_DIR =="
if [ -f "$GIT_DIR/HEAD" ]; then
    echo "Already initialized, leaving as-is."
else
    # $GIT_DIR already exists (pre-created above) - git init --bare
    # initializes into it in place, it does not need to create the dir itself.
    git init --bare "$GIT_DIR"
fi

echo "== Deploy worktree: $WORK_TREE =="
mkdir -p "$WORK_TREE"
touch "$WORK_TREE/deploy.log"

echo "== Secrets: $ENV_FILE =="
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"
if [ -f "$ENV_FILE" ]; then
    echo "Already exists - leaving untouched (not rotating an existing DB password)."
else
    umask 077
    {
        echo "# Generated by setup-box.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        echo "# LAN-only test deploy - never commit this file, never echo it to a shared terminal."
        echo
        echo "POSTGRES_USER=dagrofashield"
        echo "POSTGRES_PASSWORD=$(openssl rand -base64 32)"
        echo "POSTGRES_DB=dagrofashield"
        echo
        echo "JWT_ACCESS_SECRET=$(openssl rand -base64 48)"
        echo "JWT_ACCESS_EXPIRES_IN=15m"
        echo "JWT_REFRESH_EXPIRES_IN=7d"
        echo
        echo "# Public LAN URL of the frontend - used for CORS."
        echo "FRONTEND_ORIGIN=http://192.168.86.163:3000"
        echo
        echo "# Entra ID / OIDC left blank on purpose: the app boots with Entra"
        echo "# disabled and falls back to the local seeded admin account only."
        echo "# See README.md 'Important: this environment could not run Node/npm/Docker'"
        echo "# and backend/src/common/config/env.validation.ts."
        echo "ENTRA_TENANT_ID="
        echo "ENTRA_CLIENT_ID="
        echo "ENTRA_CLIENT_SECRET="
        echo "ENTRA_REDIRECT_URI="
        echo "ENTRA_DEFAULT_ROLE=AUDITOR"
    } >"$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "Generated $ENV_FILE (mode 600). Contents not printed - see the file"
    echo "directly on the box if you need to inspect it."
fi

echo "== Installing post-receive hook =="
install -m 0755 "$HERE/post-receive" "$GIT_DIR/hooks/post-receive"
echo "Installed $GIT_DIR/hooks/post-receive"

cat <<EOF

Setup complete.

Next, from your LOCAL machine:
  git remote add box ssh://home@192.168.86.163/opt/dagrofashield.git
  git push box main

Then tail the deploy log on the box:
  tail -f $WORK_TREE/deploy.log
EOF
